### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by bhskr44** [bhskr44/capstone-project-two#21]
# Links 
[Project Link](https://github.com/bhskr44/capstone-project-two)
[Kanban Board](https://github.com/users/bhskr44/projects/6)

## Number of People Working in the team
- Two

**Comment by julie-ify** [comment]
Hi @bhskr44 and @Alabi12,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should provide the link to the kanban board, not your repository

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AmaduKamara** [comment]
# Status: Required Changes ♻️♻️♻️ 

Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used the template given 👍 

## Required Changes ♻️
_Check the comments under the review._

- [ ] It's required that for a group of 2 students for this project, you should remove the tasks for group C and have only 15 tasks remaining in the project. Currently, you shared the tasks meant for the group-C student but it's required you have only 15 tasks remaining and the ones for group C should be removed. Basically, you are not to do those tasks, except if you guys have the time and can do that but for the Kanban board, kindly remove them 👍 
- [ ] Also, please add two assignees for tasks that are marked as group tasks. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by mckent05** [comment]
Hi team,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done and all the best with your project! 🎉
![approved](https://user-images.githubusercontent.com/73607512/203328008-0f00b810-04b2-4635-9b0c-2e7df26c3af9.gif)
 

## Highlights
- All cards have been assigned properly 👍 👍 
- Kanban board is setup correctly 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
